/* Generated by train/train.py - do not edit. */
#ifndef TAP_RHYTHM_MODEL_DATA_H_
#define TAP_RHYTHM_MODEL_DATA_H_

#define NUM_CLASSES   5
#define NUM_INTERVALS 5
#define NUM_TESTS     5

extern const unsigned char g_tap_model[];
extern const unsigned int g_tap_model_len;
extern const char *const g_class_names[NUM_CLASSES];

/* Noise-free feature vectors used by the boot self-test. */
extern const float g_test_features[NUM_TESTS][NUM_INTERVALS];
extern const int g_test_labels[NUM_TESTS];

#endif /* TAP_RHYTHM_MODEL_DATA_H_ */
